### ISSUE TITLE
Imgur upload problem

### ISSUE THREAD

**Issue by dzik87** [dzik87/D2Dropper#3]
`Access to XMLHttpRequest at 'https://api.imgur.com/3/image' from origin 'http://localhost:666' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

Find solution.

**Comment by BjarkeM** [comment]
It's a problem because the port you are hosting it on is not the same, resulting in the URL not matching. This means that the origin defined by access-control-allow-origin: '*' is invalid and the browser errors out.

host it on port 80, or behind a real domain with https, behind a reverse proxy or whatever.

**Comment by e-n-g** [comment]
Accessing dropper via an IP should solve it, no need to move the port or host it on a real domain. I've tried with port 80 and 666 and they both work.

So either use 127.0.0.1 instead of localhost or whatever IP the computer that is running dropper is assigned (most routers give something like 192.168.1.#)

**Comment by 77920** [comment]
I am still having this issue using 192.168.x.x  or 127.0.0.1:666
the problem i'm being faced with is when config.php showaccounts=True; imgur uploads won't work.
I receive a Access to i.imgur.com was denied You don't have authorization to view this page.
HTTP ERROR 403 from imgur when right clicking a single item and trying to upload to imgur.
Can't seem to find a resolution to it.
